command: ["uvicorn", "src.main:app"]

env:
# Authentication Mode
# Set to 'true' to enable per-user authentication using Databricks Apps headers
# Set to 'false' for app-level authentication (default)
  - name: 'USER_BASED_AUTHENTICATION'
    value: 'false'
    
  - name: 'DATABRICKS_DATABASE_INSTANCE'
    value: 'your_db_instance_name'
  - name: 'DATABRICKS_DATABASE_NAME'
    value: 'your_database_name'
  - name: 'DATABRICKS_DATABASE_PORT'
    value: '5432'

  - name: 'DEFAULT_POSTGRES_SCHEMA'
    value: 'public'
  - name: 'DEFAULT_POSTGRES_TABLE'
    value: 'orders_synced'

  - name: 'DB_POOL_SIZE'
    value: '5'
  - name: 'DB_MAX_OVERFLOW'
    value: '10'
  - name: 'DB_COMMAND_TIMEOUT'
    value: '30'
  - name: 'DB_POOL_TIMEOUT'
    value: '10'
  - name: 'DB_POOL_RECYCLE_INTERVAL'
    value: '3600'
