command: ["uvicorn", "src.app:app"]

env:
# Authentication Mode
# Set to 'true' to enable per-user authentication using Databricks Apps headers
# Set to 'false' for app-level authentication (default)
  - name: 'USER_BASED_AUTHENTICATION'
    value: 'false'

  - name: 'LAKEBASE_INSTANCE_NAME'
    value: 'gdoyle-fastapi-demo'
  - name: 'LAKEBASE_DATABASE_NAME'
    value: 'gdoyle-database'
  - name: 'LAKEBASE_CATALOG_NAME'
    value: 'gdd-lakebase-catalog'
  - name: 'SYNCHED_TABLE_STORAGE_CATALOG'
    value: 'grant_doyle'
  - name: 'SYNCHED_TABLE_STORAGE_SCHEMA'
    value: 'lakebase_sme_demo'
  - name: 'DATABRICKS_DATABASE_PORT'
    value: '5432'

  - name: 'DEFAULT_POSTGRES_SCHEMA'
    value: 'public'
  - name: 'DEFAULT_POSTGRES_TABLE'
    value: 'orders_synced'

  - name: 'DB_POOL_SIZE'
    value: '5'
  - name: 'DB_MAX_OVERFLOW'
    value: '10'
  - name: 'DB_COMMAND_TIMEOUT'
    value: '30'
  - name: 'DB_POOL_TIMEOUT'
    value: '10'